* Προβλήματα
** Υποδιαστολη
*** Το προβλημα
    Το προβλημα αυτο εχει να κανει με τον τροπο που η Java κανει
    floating point πράξεις. Συγκεκριμενα επειδη μαλλον ξερει πως δεν θα
    τα καταφερει να βρισκει παντα σωστο αποτελεσμα σε ολες τις πραξεις
    λογω του πεπερασμενου μεγεθους του double, βρεισκει ελαχιστα λαθως
    αποτελεσματα μερικες φορες ακομα και οταν εχει αρκετα bits ωστε να
    εκφρασει το σωστο. Για παραδειγμα εκει που ο operand ειναι 1.123
    και ο χρηστης παταει το 1, η Operand θα κανει την πραξη 1.123 + 1 *
    10**-4. Αυτου του ειδους οι πραξεις ειναι πιθανο να βγαλου
    αποτελεσμα που να μοιαζει με 1.12309999999 η 1.1231000000002.

*** Η λυση
    Η Operand ξερει ποσα δεκαδικα ψηφια πρεπει να υπαρχουν καθε φορα
    με αποτελεσμα να στρογγυλοποιει το αποτελεσμα της πραξης καθε φορα
    που ο χρηστης παταει ενα κουμπι. Επιπλεον μολις υπολογιστει ενα
    αποτελεσμα και μπει στην Operand υπολογιζουμε το ποσα δεκαδικα
    (max 10) υπαρχουν στον αριθμο ωστε ακομα και τοτε να ξερουμε πως
    να χειριστουμε επιπλεον input.
